
model:
  # if precision=16 then mixed precision is used:
  precision: 32

  # weather to weight the losses according to the number of samples per class
  use_weighted_loss: false

  # whether to download a pretrained network
  use_pretrained: false