this_config_file: "binary_config.yaml"

# --------------------------------------------------------------------------------------
# ==================
# technical:
# ==================

experiment_name: Resnet_classifier_plankton_binary

# Number of GPUs per Node (On strand max. is 1). If 0 then use CPUs:
gpus: 1

# CPUs for the dataloader. For windows this should be 0, otherwise it will crash:
# Also with streaming data this should be 0:
num_workers: 20

super_classes:
  Something:
    - Jellyfish
    - Zooplankton_Other
    - Gastropoda
    - Dinoflagellates
    - Noctiluca
    - Phytoplankton
    - Trichodesmium
    - Foraminifera
    - Appendicularia
    - Ceratocoris
    - Trochophora
    - Radiolaria
    - Copepods
    - MarineSnow_Comet
    - MarineSnow_Detritus
    - MarineSnow_FaecalPellet
    - MarineSnow_Jelly
  Nothing:
    - Blurry
    - Bubbles

excluded_classes: []
