name: plankton

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  - pip
  - cudatoolkit
  - pytorch
  - natsort
  - pre-commit
  - black
  - isort
  - flake8
  - tensorboard
  - torchvision
  - pytorch-lightning
  - torchmetrics
  - matplotlib
  - ipython
  - hydra-core
  - jupyterlab
  - scikit-learn
  - rich
  - pandas
  - dask
  - distributed
  - numpy
  - seaborn
  - python-dotenv
  - onnx
  - pillow
  - tqdm
  - pip:
      - onnxruntime-gpu
      - lightning-bolts
      - hydra-colorlog
      - hydra-optuna-sweeper
      - hydra-submitit-launcher
      - test-tube
      - fairscale
      - catalyst
      - https://github.com/ufoym/imbalanced-dataset-sampler/archive/master.zip # torchsampler
