name: plankton

channels:
  - nvidia
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.3
  - pytorch>=1.11
  - natsort
  - pre-commit
  - black
  - isort
  - flake8
  - tensorboard
  - torchvision>=0.12
  - pytorch-lightning>=1.6
  - torchmetrics
  - matplotlib
  - ipython
  - hydra-core=1.1
  - jupyterlab
  - scikit-learn
  - rich
  - pandas
  - dask
  - distributed
  - numpy
  - seaborn
  - python-dotenv
  - onnx
  - pillow
  - pytest
  - tqdm
  - webdataset
  - pip:
      - onnxruntime-gpu
      - lightning-bolts
      - torch-tb-profiler
      - hydra-colorlog
      - hydra-optuna-sweeper
      - hydra-submitit-launcher
      - test-tube
      - catalyst
      - git+https://github.com/ufoym/imbalanced-dataset-sampler.git # torchsampler
