name: plankton
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - ipython=7.22.0
  - ipywidgets
  - numpy
  - pytorch
  - cudatoolkit=11.1
  - pytorch-lightning
  - torchvision
  - scikit-learn
  - pillow
  - tqdm
  - matplotlib
  - tensorboard
  - simpleitk
  - onnx
  - pip
  - pip:
      - onnxruntime
      - test-tube
      - fairscale
      - torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html