[tool.vulture]
exclude = ["conf/", "data/", "docs/", "notebooks/", "output*/", "src/external/"]
make_whitelist = false
min_confidence = 100
paths = ["main.py", "src/"]
sort_by_size = true
verbose = false


[tool.pylint]
max-line-length = 120
exclude-protected = ["_asdict", "_fields", "_replace", "_source", "_make", "_target_"]
logging-format-style = "new"
disable=[
    "logging-fstring-interpolation",
    "too-many-branches",
    "too-many-statements",
    "logging-fstring-interpolation",
    "too-many-locals",
    "unspecified-encoding",
    "too-many-ancestors",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-arguments",
    "missing-module-docstring",  # docstrings are handled by interrogate, so we don't need pylint to check them again
    "missing-class-docstring",
    "missing-function-docstring",
]
generated-members=["torch.*"]
ignore = ["tests"]

[tool.docformatter]
recursive = true
wrap-summaries = 79
wrap-descriptions = 72
blank = true
force-wrap = true

[tool.pytest.ini_options]
pythonpath = ["."]
