# @package hydra.launcher
defaults:
  - submitit_slurm
  - _self_

timeout_min: 4000 # maximum time for the job in minutes
cpus_per_task: 40
tasks_per_node: ${trainer.gpus} # == gpus_per_node
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: pGPU32
signal_delay_s: 120
additional_parameters: { exclusive: true, signal: "SIGUSR1@90" }
array_parallelism: 256
setup: ["source activate hydra"]
