defaults:
  - _self_
  - base_config
  - lightning_module: default
  - datamodule: plankton
  - datamodule/train_transforms: default
  - datamodule/valid_transforms: default
  - model/feature_extractor: resnet
  - model/classifier: linear
  - trainer: default
  - optimizer: adam
  - loss: nll_loss
  - logger/tensorboard: tensorboard
  - callbacks/checkpoint: model_checkpoint

  - override hydra/launcher: strand

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

output_dir_base_path: /gpfs/work/machnitz/plankton_logs

logger:
  tensorboard:
    default_hp_metric: False # important to be False, when we want to use own hp_metrics


hydra:
  sweep:
    subdir: ${output_dir_base_path}/multirun/${hydra.job.num}_${hydra.job.num}_${hydra.job.override_dirname}
  run:
    dir: ${output_dir_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}