defaults:
  - _self_
  - base_config
  - lightning_module: default
  - datamodule: plankton
  - datamodule/train_transforms: default
  - datamodule/valid_transforms: default
  - model/feature_extractor: resnet
  - model/classifier: linear
  - trainer: default
  - optimizer: adam
  - loss: nll_loss
  - logger/tensorboard: tensorboard
  - callbacks/checkpoint: model_checkpoint

  - override hydra/launcher: strand

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

logger:
  tensorboard:
    default_hp_metric: False # important to be False, when we want to use own hp_metrics
