# ==================
# Paths:
# ==================
paths:
  # top path where to find all plankton data:
  plankton_data_base_path: "/gpfs/work/machnitz/plankton_dataset"

  # The folder structure is Sorted/ClassName/DateFolder/*.png
  new_sorted_plankton_data: "new_data/4David/M160/Sorted"

  # Contains unsorted data in date-sorted subfolders. Files end on .png
  new_unsorted_plankton_data: "new_data/4David/HE570/rois/20*/20*"

  planktonnet_data: "PlanktonNet/DYB-PlanktonNet_V1.0_EN"

  canadian_data: "canadian_dataset"
