_target_: torchvision.transforms.Compose

transforms:
  - _target_: torchvision.transforms.TrivialAugmentWide

  - _target_: torchvision.transforms.Resize
    size:
      - 128
      - 128
  - _target_: torchvision.transforms.ToTensor
