_target_: torchvision.transforms.Compose

transforms:
  - _target_: torchvision.transforms.RandomResizedCrop
    size:
      - 128
      - 128
    scale:
      - 0.7
      - 1.0

  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5

  - _target_: torchvision.transforms.RandomVerticalFlip
    p: 0.5

#  - _target_: torchvision.transforms.AugMix

  - _target_: torchvision.transforms.GaussianBlur
    kernel_size:
      - 5
      - 5

  - _target_: torchvision.transforms.RandomAutocontrast

  - _target_: torchvision.transforms.ColorJitter


  - _target_: torchvision.transforms.ToTensor
