_target_: torchvision.transforms.Compose

transforms:
  - _target_: torchvision.transforms.RandomResizedCrop
    size:
      - 32
      - 32

  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5

  - _target_: torchvision.transforms.RandomApply
    transforms:
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
    p: 0.8

  - _target_: torchvision.transforms.RandomGrayscale
    p: 0.2

  - _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean:
          - 0.4913725490196078
          - 0.4823529411764706
          - 0.4466666666666667
        std:
          - 0.24705882352941178
          - 0.24352941176470588
          - 0.2615686274509804


