_target_: torchvision.transforms.Compose

transforms:
  - _target_: torchvision.transforms.RandomCrop
    size:
      - 22
      - 22

  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    hue: 0.5

  - _target_: torchvision.transforms.RandomRotation
    degrees: 45

  - _target_: torchvision.transforms.ToTensor
