defaults:
  - plankton_datamodule_base

excluded_labels: null
batch_size: 16
num_workers: 0
train_split:  0.8
validation_split:  0.1
shuffle_train_dataset: true
shuffle_validation_dataset:  false
shuffle_test_dataset: false
preload_dataset: false
use_planktonnet_data: false
use_klas_data: true
use_canadian_data: False
super_classes:  null
oversample_data: true
final_image_size: (512, 512)
klas_data_path: "/gpfs/work/machnitz/plankton_dataset/new_data/4David/M160/Sorted"
planktonnet_data_path: "/gpfs/work/machnitz/plankton_dataset/PlanktonNet/DYB-PlanktonNet_V1.0_EN"
canadian_data_path: "/gpfs/work/machnitz/plankton_dataset/canadian_dataset"
random_seed: ${/random_seed}
