defaults:
  - plankton_datamodule_base
  - dataset: default

excluded_labels: ["blurry", "bubbles"] # has to be  a list
batch_size: 16
num_workers: 0
train_split: 0.8
validation_split: 0.1
shuffle_train_dataset: true
shuffle_validation_dataset: false
shuffle_test_dataset: false
preload_dataset: false
use_planktonnet_data: false
use_klas_data: true
use_canadian_data: False
super_classes:
  {
    MarineSnow:
      [
        "MarineSnow_Comet",
        "MarineSnow_Detritus",
        "MarineSnow_FaecalPellet",
        "MarineSnow_Jelly",
      ],
    Radiolaria: ["Radiolaria", "Foraminifera"],
  }
oversample_data: true
data_base_path: /gpfs/work/machnitz/plankton_dataset/
klas_data_path: ${datamodule.data_base_path}new_data/4David/M160/Sorted
planktonnet_data_path: ${datamodule.data_base_path}PlanktonNet/DYB-PlanktonNet_V1.0_EN
canadian_data_path: ${datamodule.data_base_path}canadian_dataset
random_seed: ${random_seed}
